# Master Configuration for CodeCrest_AIChatBot
client_id = "708b332fafb83cdf9816ec531b2c4e6d"
name = "CodeCrest_AIChatBot"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_products,read_content"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[app_proxy]
url = "https://shopify.dev/apps/default-app-home"
subpath = "chat-api"
prefix = "apps"
